language: python
deploy:
  provider: gae
  keyfile: credentials.tar.gz
  project: pyramid-prototype
script: python test_main.py
before_install:
- openssl aes-256-cbc -K $encrypted_80de6bc272ab_key -iv $encrypted_80de6bc272ab_iv
  -in client-secret.json.enc -out client-secret.json -d
